import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/main/header";
import Footer from "@/components/main/footer";



export const metadata: Metadata = {
  title: "자유공간",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="outline">

        <header>
          <Header />
        </header>

        <main>
        {children}
        </main>

        <footer>
          <Footer />
        </footer>

      </body>
    </html>
  );
}
