import type { Metadata } from "next";
import "./globals.css";
import Body from "./body";



export const metadata: Metadata = {
  title: "자유공간",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="ko">
        <Body>
          {children}
        </Body>
    </html>
  );
}
